// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Profile struct {
	PeerID               string               `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	Handle               string               `protobuf:"bytes,2,opt,name=handle,proto3" json:"handle,omitempty"`
	Name                 string               `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Location             string               `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	About                string               `protobuf:"bytes,5,opt,name=about,proto3" json:"about,omitempty"`
	ShortDescription     string               `protobuf:"bytes,6,opt,name=shortDescription,proto3" json:"shortDescription,omitempty"`
	Nsfw                 bool                 `protobuf:"varint,7,opt,name=nsfw,proto3" json:"nsfw,omitempty"`
	Vendor               bool                 `protobuf:"varint,8,opt,name=vendor,proto3" json:"vendor,omitempty"`
	Moderator            bool                 `protobuf:"varint,9,opt,name=moderator,proto3" json:"moderator,omitempty"`
	ModeratorInfo        *Moderator           `protobuf:"bytes,10,opt,name=moderatorInfo,proto3" json:"moderatorInfo,omitempty"`
	ContactInfo          *Profile_Contact     `protobuf:"bytes,11,opt,name=contactInfo,proto3" json:"contactInfo,omitempty"`
	Colors               *Profile_Colors      `protobuf:"bytes,12,opt,name=colors,proto3" json:"colors,omitempty"`
	AvatarHashes         *Profile_Image       `protobuf:"bytes,13,opt,name=avatarHashes,proto3" json:"avatarHashes,omitempty"`
	HeaderHashes         *Profile_Image       `protobuf:"bytes,14,opt,name=headerHashes,proto3" json:"headerHashes,omitempty"`
	Stats                *Profile_Stats       `protobuf:"bytes,15,opt,name=stats,proto3" json:"stats,omitempty"`
	BitcoinPubkey        string               `protobuf:"bytes,16,opt,name=bitcoinPubkey,proto3" json:"bitcoinPubkey,omitempty"`
	LastModified         *timestamp.Timestamp `protobuf:"bytes,17,opt,name=lastModified,proto3" json:"lastModified,omitempty"`
	Currencies           []string             `protobuf:"bytes,18,rep,name=currencies,proto3" json:"currencies,omitempty"`
	WalletAutoLockTime   uint32               `protobuf:"varint,19,opt,name=walletAutoLockTime,proto3" json:"walletAutoLockTime,omitempty"`
	Version              uint32               `protobuf:"varint,20,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Profile) Reset()         { *m = Profile{} }
func (m *Profile) String() string { return proto.CompactTextString(m) }
func (*Profile) ProtoMessage()    {}
func (*Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile.Unmarshal(m, b)
}
func (m *Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile.Marshal(b, m, deterministic)
}
func (m *Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile.Merge(m, src)
}
func (m *Profile) XXX_Size() int {
	return xxx_messageInfo_Profile.Size(m)
}
func (m *Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Profile proto.InternalMessageInfo

func (m *Profile) GetPeerID() string {
	if m != nil {
		return m.PeerID
	}
	return ""
}

func (m *Profile) GetHandle() string {
	if m != nil {
		return m.Handle
	}
	return ""
}

func (m *Profile) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Profile) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Profile) GetAbout() string {
	if m != nil {
		return m.About
	}
	return ""
}

func (m *Profile) GetShortDescription() string {
	if m != nil {
		return m.ShortDescription
	}
	return ""
}

func (m *Profile) GetNsfw() bool {
	if m != nil {
		return m.Nsfw
	}
	return false
}

func (m *Profile) GetVendor() bool {
	if m != nil {
		return m.Vendor
	}
	return false
}

func (m *Profile) GetModerator() bool {
	if m != nil {
		return m.Moderator
	}
	return false
}

func (m *Profile) GetModeratorInfo() *Moderator {
	if m != nil {
		return m.ModeratorInfo
	}
	return nil
}

func (m *Profile) GetContactInfo() *Profile_Contact {
	if m != nil {
		return m.ContactInfo
	}
	return nil
}

func (m *Profile) GetColors() *Profile_Colors {
	if m != nil {
		return m.Colors
	}
	return nil
}

func (m *Profile) GetAvatarHashes() *Profile_Image {
	if m != nil {
		return m.AvatarHashes
	}
	return nil
}

func (m *Profile) GetHeaderHashes() *Profile_Image {
	if m != nil {
		return m.HeaderHashes
	}
	return nil
}

func (m *Profile) GetStats() *Profile_Stats {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *Profile) GetBitcoinPubkey() string {
	if m != nil {
		return m.BitcoinPubkey
	}
	return ""
}

func (m *Profile) GetLastModified() *timestamp.Timestamp {
	if m != nil {
		return m.LastModified
	}
	return nil
}

func (m *Profile) GetCurrencies() []string {
	if m != nil {
		return m.Currencies
	}
	return nil
}

func (m *Profile) GetWalletAutoLockTime() uint32 {
	if m != nil {
		return m.WalletAutoLockTime
	}
	return 0
}

func (m *Profile) GetVersion() uint32 {
	if m != nil {
		return m.Version
	}
	return 0
}

type Profile_Contact struct {
	Website              string                   `protobuf:"bytes,1,opt,name=website,proto3" json:"website,omitempty"`
	Email                string                   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNumber          string                   `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Social               []*Profile_SocialAccount `protobuf:"bytes,4,rep,name=social,proto3" json:"social,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Profile_Contact) Reset()         { *m = Profile_Contact{} }
func (m *Profile_Contact) String() string { return proto.CompactTextString(m) }
func (*Profile_Contact) ProtoMessage()    {}
func (*Profile_Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 0}
}

func (m *Profile_Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_Contact.Unmarshal(m, b)
}
func (m *Profile_Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_Contact.Marshal(b, m, deterministic)
}
func (m *Profile_Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_Contact.Merge(m, src)
}
func (m *Profile_Contact) XXX_Size() int {
	return xxx_messageInfo_Profile_Contact.Size(m)
}
func (m *Profile_Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_Contact proto.InternalMessageInfo

func (m *Profile_Contact) GetWebsite() string {
	if m != nil {
		return m.Website
	}
	return ""
}

func (m *Profile_Contact) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Profile_Contact) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *Profile_Contact) GetSocial() []*Profile_SocialAccount {
	if m != nil {
		return m.Social
	}
	return nil
}

type Profile_SocialAccount struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Proof                string   `protobuf:"bytes,3,opt,name=proof,proto3" json:"proof,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_SocialAccount) Reset()         { *m = Profile_SocialAccount{} }
func (m *Profile_SocialAccount) String() string { return proto.CompactTextString(m) }
func (*Profile_SocialAccount) ProtoMessage()    {}
func (*Profile_SocialAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 1}
}

func (m *Profile_SocialAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_SocialAccount.Unmarshal(m, b)
}
func (m *Profile_SocialAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_SocialAccount.Marshal(b, m, deterministic)
}
func (m *Profile_SocialAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_SocialAccount.Merge(m, src)
}
func (m *Profile_SocialAccount) XXX_Size() int {
	return xxx_messageInfo_Profile_SocialAccount.Size(m)
}
func (m *Profile_SocialAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_SocialAccount.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_SocialAccount proto.InternalMessageInfo

func (m *Profile_SocialAccount) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Profile_SocialAccount) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Profile_SocialAccount) GetProof() string {
	if m != nil {
		return m.Proof
	}
	return ""
}

type Profile_Image struct {
	Tiny                 string   `protobuf:"bytes,1,opt,name=tiny,proto3" json:"tiny,omitempty"`
	Small                string   `protobuf:"bytes,2,opt,name=small,proto3" json:"small,omitempty"`
	Medium               string   `protobuf:"bytes,3,opt,name=medium,proto3" json:"medium,omitempty"`
	Large                string   `protobuf:"bytes,4,opt,name=large,proto3" json:"large,omitempty"`
	Original             string   `protobuf:"bytes,5,opt,name=original,proto3" json:"original,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_Image) Reset()         { *m = Profile_Image{} }
func (m *Profile_Image) String() string { return proto.CompactTextString(m) }
func (*Profile_Image) ProtoMessage()    {}
func (*Profile_Image) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 2}
}

func (m *Profile_Image) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_Image.Unmarshal(m, b)
}
func (m *Profile_Image) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_Image.Marshal(b, m, deterministic)
}
func (m *Profile_Image) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_Image.Merge(m, src)
}
func (m *Profile_Image) XXX_Size() int {
	return xxx_messageInfo_Profile_Image.Size(m)
}
func (m *Profile_Image) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_Image.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_Image proto.InternalMessageInfo

func (m *Profile_Image) GetTiny() string {
	if m != nil {
		return m.Tiny
	}
	return ""
}

func (m *Profile_Image) GetSmall() string {
	if m != nil {
		return m.Small
	}
	return ""
}

func (m *Profile_Image) GetMedium() string {
	if m != nil {
		return m.Medium
	}
	return ""
}

func (m *Profile_Image) GetLarge() string {
	if m != nil {
		return m.Large
	}
	return ""
}

func (m *Profile_Image) GetOriginal() string {
	if m != nil {
		return m.Original
	}
	return ""
}

type Profile_Colors struct {
	Primary              string   `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	Secondary            string   `protobuf:"bytes,2,opt,name=secondary,proto3" json:"secondary,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Highlight            string   `protobuf:"bytes,4,opt,name=highlight,proto3" json:"highlight,omitempty"`
	HighlightText        string   `protobuf:"bytes,5,opt,name=highlightText,proto3" json:"highlightText,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_Colors) Reset()         { *m = Profile_Colors{} }
func (m *Profile_Colors) String() string { return proto.CompactTextString(m) }
func (*Profile_Colors) ProtoMessage()    {}
func (*Profile_Colors) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 3}
}

func (m *Profile_Colors) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_Colors.Unmarshal(m, b)
}
func (m *Profile_Colors) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_Colors.Marshal(b, m, deterministic)
}
func (m *Profile_Colors) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_Colors.Merge(m, src)
}
func (m *Profile_Colors) XXX_Size() int {
	return xxx_messageInfo_Profile_Colors.Size(m)
}
func (m *Profile_Colors) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_Colors.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_Colors proto.InternalMessageInfo

func (m *Profile_Colors) GetPrimary() string {
	if m != nil {
		return m.Primary
	}
	return ""
}

func (m *Profile_Colors) GetSecondary() string {
	if m != nil {
		return m.Secondary
	}
	return ""
}

func (m *Profile_Colors) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Profile_Colors) GetHighlight() string {
	if m != nil {
		return m.Highlight
	}
	return ""
}

func (m *Profile_Colors) GetHighlightText() string {
	if m != nil {
		return m.HighlightText
	}
	return ""
}

type Profile_Stats struct {
	FollowerCount        uint32   `protobuf:"varint,1,opt,name=followerCount,proto3" json:"followerCount,omitempty"`
	FollowingCount       uint32   `protobuf:"varint,2,opt,name=followingCount,proto3" json:"followingCount,omitempty"`
	ListingCount         uint32   `protobuf:"varint,3,opt,name=listingCount,proto3" json:"listingCount,omitempty"`
	RatingCount          uint32   `protobuf:"varint,4,opt,name=ratingCount,proto3" json:"ratingCount,omitempty"`
	PostCount            uint32   `protobuf:"varint,5,opt,name=postCount,proto3" json:"postCount,omitempty"`
	AverageRating        float32  `protobuf:"fixed32,6,opt,name=averageRating,proto3" json:"averageRating,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Profile_Stats) Reset()         { *m = Profile_Stats{} }
func (m *Profile_Stats) String() string { return proto.CompactTextString(m) }
func (*Profile_Stats) ProtoMessage()    {}
func (*Profile_Stats) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0, 4}
}

func (m *Profile_Stats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Profile_Stats.Unmarshal(m, b)
}
func (m *Profile_Stats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Profile_Stats.Marshal(b, m, deterministic)
}
func (m *Profile_Stats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Profile_Stats.Merge(m, src)
}
func (m *Profile_Stats) XXX_Size() int {
	return xxx_messageInfo_Profile_Stats.Size(m)
}
func (m *Profile_Stats) XXX_DiscardUnknown() {
	xxx_messageInfo_Profile_Stats.DiscardUnknown(m)
}

var xxx_messageInfo_Profile_Stats proto.InternalMessageInfo

func (m *Profile_Stats) GetFollowerCount() uint32 {
	if m != nil {
		return m.FollowerCount
	}
	return 0
}

func (m *Profile_Stats) GetFollowingCount() uint32 {
	if m != nil {
		return m.FollowingCount
	}
	return 0
}

func (m *Profile_Stats) GetListingCount() uint32 {
	if m != nil {
		return m.ListingCount
	}
	return 0
}

func (m *Profile_Stats) GetRatingCount() uint32 {
	if m != nil {
		return m.RatingCount
	}
	return 0
}

func (m *Profile_Stats) GetPostCount() uint32 {
	if m != nil {
		return m.PostCount
	}
	return 0
}

func (m *Profile_Stats) GetAverageRating() float32 {
	if m != nil {
		return m.AverageRating
	}
	return 0
}

func init() {
	proto.RegisterType((*Profile)(nil), "Profile")
	proto.RegisterType((*Profile_Contact)(nil), "Profile.Contact")
	proto.RegisterType((*Profile_SocialAccount)(nil), "Profile.SocialAccount")
	proto.RegisterType((*Profile_Image)(nil), "Profile.Image")
	proto.RegisterType((*Profile_Colors)(nil), "Profile.Colors")
	proto.RegisterType((*Profile_Stats)(nil), "Profile.Stats")
}

func init() { proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504) }

var fileDescriptor_744bf7a47b381504 = []byte{
	// 740 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0xcd, 0x8e, 0xdb, 0x36,
	0x10, 0x86, 0xd6, 0x7f, 0x6b, 0xda, 0xde, 0xdd, 0xb2, 0x41, 0x40, 0x08, 0x45, 0x6b, 0x04, 0x41,
	0x6b, 0xf4, 0xa0, 0x14, 0xee, 0xbd, 0x40, 0x9a, 0x1c, 0xba, 0x40, 0x53, 0x04, 0x4a, 0x7a, 0xe9,
	0x8d, 0x92, 0xc6, 0x12, 0x11, 0x4a, 0x14, 0x48, 0xca, 0xae, 0xd1, 0x47, 0xe8, 0x0b, 0xf4, 0x75,
	0xfa, 0x24, 0x7d, 0x95, 0x82, 0x43, 0x4a, 0xb6, 0x92, 0xdc, 0xf8, 0x7d, 0xf3, 0xcd, 0xf8, 0x13,
	0xf9, 0x8d, 0xc9, 0xa6, 0xd5, 0xea, 0x20, 0x24, 0x24, 0xad, 0x56, 0x56, 0xc5, 0xdf, 0x94, 0x4a,
	0x95, 0x12, 0x5e, 0x20, 0xca, 0xba, 0xc3, 0x0b, 0x2b, 0x6a, 0x30, 0x96, 0xd7, 0x6d, 0x10, 0xdc,
	0xd7, 0xaa, 0x00, 0xcd, 0xad, 0xd2, 0x9e, 0x78, 0xf6, 0xef, 0x8a, 0x2c, 0xde, 0xfa, 0x19, 0xf4,
	0x29, 0x99, 0xb7, 0x00, 0xfa, 0xf1, 0x35, 0x8b, 0xb6, 0xd1, 0x6e, 0x99, 0x06, 0xe4, 0xf8, 0x8a,
	0x37, 0x85, 0x04, 0x76, 0xe3, 0x79, 0x8f, 0x28, 0x25, 0xd3, 0x86, 0xd7, 0xc0, 0x26, 0xc8, 0xe2,
	0x99, 0xc6, 0xe4, 0x56, 0xaa, 0x9c, 0x5b, 0xa1, 0x1a, 0x36, 0x45, 0x7e, 0xc0, 0xf4, 0x09, 0x99,
	0xf1, 0x4c, 0x75, 0x96, 0xcd, 0xb0, 0xe0, 0x01, 0xfd, 0x9e, 0x3c, 0x98, 0x4a, 0x69, 0xfb, 0x1a,
	0x4c, 0xae, 0x45, 0x8b, 0x9d, 0x73, 0x14, 0x7c, 0xc2, 0xe3, 0x2f, 0x9a, 0xc3, 0x89, 0x2d, 0xb6,
	0xd1, 0xee, 0x36, 0xc5, 0xb3, 0x73, 0x77, 0x84, 0xa6, 0x50, 0x9a, 0xdd, 0x22, 0x1b, 0x10, 0xfd,
	0x8a, 0x2c, 0x87, 0x8f, 0x65, 0x4b, 0x2c, 0x5d, 0x08, 0xfa, 0x03, 0xd9, 0x0c, 0xe0, 0xb1, 0x39,
	0x28, 0x46, 0xb6, 0xd1, 0x6e, 0xb5, 0x27, 0xc9, 0x9b, 0x9e, 0x4d, 0xc7, 0x02, 0xba, 0x27, 0xab,
	0x5c, 0x35, 0x96, 0xe7, 0x16, 0xf5, 0x2b, 0xd4, 0x3f, 0x24, 0xe1, 0xf2, 0x92, 0x57, 0xbe, 0x96,
	0x5e, 0x8b, 0xe8, 0x77, 0x64, 0x9e, 0x2b, 0xa9, 0xb4, 0x61, 0x6b, 0x94, 0xdf, 0x5f, 0xc9, 0x1d,
	0x9d, 0x86, 0x32, 0xdd, 0x93, 0x35, 0x3f, 0x72, 0xcb, 0xf5, 0x2f, 0xdc, 0x54, 0x60, 0xd8, 0x06,
	0xe5, 0x77, 0x83, 0xfc, 0xb1, 0xe6, 0x25, 0xa4, 0x23, 0x8d, 0xeb, 0xa9, 0x80, 0x17, 0xd0, 0xf7,
	0xdc, 0x7d, 0xbe, 0xe7, 0x5a, 0x43, 0x9f, 0x93, 0x99, 0xb1, 0xdc, 0x1a, 0x76, 0xff, 0x91, 0xf8,
	0x9d, 0x63, 0x53, 0x5f, 0xa4, 0xcf, 0xc9, 0x26, 0x13, 0x36, 0x57, 0xa2, 0x79, 0xdb, 0x65, 0x1f,
	0xe0, 0xcc, 0x1e, 0xf0, 0x3d, 0xc6, 0x24, 0xfd, 0x89, 0xac, 0x25, 0x37, 0xf6, 0x8d, 0x2a, 0xc4,
	0x41, 0x40, 0xc1, 0xbe, 0xc0, 0x91, 0x71, 0xe2, 0x33, 0x98, 0xf4, 0x19, 0x4c, 0xde, 0xf7, 0x19,
	0x4c, 0x47, 0x7a, 0xfa, 0x35, 0x21, 0x79, 0xa7, 0x35, 0x34, 0xb9, 0x00, 0xc3, 0xe8, 0x76, 0xb2,
	0x5b, 0xa6, 0x57, 0x0c, 0x4d, 0x08, 0x3d, 0x71, 0x29, 0xc1, 0xbe, 0xec, 0xac, 0xfa, 0x55, 0xe5,
	0x1f, 0xdc, 0x20, 0xf6, 0xe5, 0x36, 0xda, 0x6d, 0xd2, 0xcf, 0x54, 0x28, 0x23, 0x8b, 0x23, 0x68,
	0xe3, 0xf2, 0xf3, 0x04, 0x45, 0x3d, 0x8c, 0xff, 0x8e, 0xc8, 0x22, 0xbc, 0x8f, 0x53, 0x9d, 0x20,
	0x33, 0xc2, 0x42, 0x48, 0x79, 0x0f, 0x5d, 0x3c, 0xa1, 0xe6, 0x42, 0x86, 0x94, 0x7b, 0x40, 0xb7,
	0x64, 0xd5, 0x56, 0xaa, 0x81, 0xdf, 0xba, 0x3a, 0x03, 0x1d, 0xb2, 0x7e, 0x4d, 0xd1, 0x84, 0xcc,
	0x8d, 0xca, 0x05, 0x97, 0x6c, 0xba, 0x9d, 0xec, 0x56, 0xfb, 0xa7, 0x97, 0x4b, 0x45, 0xfa, 0x65,
	0x9e, 0xab, 0xae, 0xb1, 0x69, 0x50, 0xc5, 0xbf, 0x93, 0xcd, 0xa8, 0xe0, 0x52, 0x6d, 0xcf, 0x6d,
	0xef, 0x07, 0xcf, 0x6e, 0x8f, 0x3a, 0x03, 0x1a, 0xf7, 0xcb, 0xfb, 0x19, 0xb0, 0x33, 0xda, 0x6a,
	0xa5, 0x0e, 0xc1, 0x8c, 0x07, 0xf1, 0x5f, 0x64, 0x86, 0x2f, 0x8e, 0xe3, 0x44, 0x73, 0x1e, 0xc6,
	0x89, 0xe6, 0xec, 0x5a, 0x4c, 0xcd, 0xe5, 0xf0, 0x6d, 0x08, 0xdc, 0xea, 0xd4, 0x50, 0x88, 0xae,
	0x0e, 0x93, 0x02, 0x72, 0x6a, 0xc9, 0x75, 0x09, 0x61, 0x83, 0x3d, 0x70, 0x96, 0x94, 0x16, 0xa5,
	0x68, 0xb8, 0x0c, 0x1b, 0x3c, 0xe0, 0xf8, 0x9f, 0x88, 0xcc, 0x7d, 0xa4, 0xdd, 0x05, 0xb7, 0x5a,
	0xd4, 0x5c, 0xf7, 0x0e, 0x7a, 0xe8, 0x36, 0xd2, 0x40, 0xae, 0x9a, 0xc2, 0xd5, 0xbc, 0x91, 0x0b,
	0x81, 0xb6, 0xe1, 0x4f, 0xdb, 0xff, 0x9b, 0xb8, 0xb3, 0xeb, 0xa8, 0x44, 0x59, 0x49, 0x51, 0x56,
	0x36, 0x98, 0xb9, 0x10, 0x2e, 0xa6, 0x03, 0x78, 0xef, 0x5a, 0xbd, 0xab, 0x31, 0x19, 0xff, 0x17,
	0x91, 0xd9, 0xbb, 0x3e, 0xd6, 0x07, 0x25, 0xa5, 0x3a, 0x81, 0x7e, 0xe5, 0x2e, 0x1e, 0xfd, 0x6d,
	0xd2, 0x31, 0x49, 0xbf, 0x25, 0x77, 0x9e, 0x10, 0x4d, 0xe9, 0x65, 0x37, 0x28, 0xfb, 0x88, 0xa5,
	0xcf, 0xc8, 0x5a, 0x0a, 0x63, 0x07, 0xd5, 0x04, 0x55, 0x23, 0xce, 0x85, 0x47, 0xf3, 0x8b, 0x64,
	0x8a, 0x92, 0x6b, 0xca, 0x7d, 0x61, 0xab, 0x8c, 0xf5, 0xf5, 0x19, 0xd6, 0x2f, 0x84, 0x73, 0xcc,
	0x8f, 0xa0, 0xdd, 0x1e, 0x63, 0x0f, 0xfe, 0x31, 0xde, 0xa4, 0x63, 0xf2, 0xe7, 0xe9, 0x1f, 0x37,
	0x6d, 0x96, 0xcd, 0x71, 0xe1, 0x7e, 0xfc, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x4c, 0xa1, 0xfb, 0x13,
	0x13, 0x06, 0x00, 0x00,
}
